-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\zynqRadioHWSWLTEDecimatorRFSoC2x2\LTE_DOWNS_ip_dut.vhd
-- Created: 2022-05-25 15:55:32
-- 
-- Generated by MATLAB 9.12 and HDL Coder 3.20
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: LTE_DOWNS_ip_dut
-- Source Path: LTE_DOWNS_ip/LTE_DOWNS_ip_dut
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY LTE_DOWNS_ip_dut IS
  PORT( clk                               :   IN    std_logic;
        reset_x                           :   IN    std_logic;
        dut_enable                        :   IN    std_logic;  -- ufix1
        rxdatai_in                        :   IN    std_logic_vector(127 DOWNTO 0);  -- ufix128
        rxdataq_in                        :   IN    std_logic_vector(127 DOWNTO 0);  -- ufix128
        rxdatai_valid                     :   IN    std_logic;  -- ufix1
        rxdataq_valid                     :   IN    std_logic;  -- ufix1
        txdatai_ready                     :   IN    std_logic;  -- ufix1
        txdataq_ready                     :   IN    std_logic;  -- ufix1
        extdatasel_in                     :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32
        ce_out_0                          :   OUT   std_logic;  -- ufix1
        ce_out_1                          :   OUT   std_logic;  -- ufix1
        txI_data                          :   OUT   std_logic_vector(15 DOWNTO 0);  -- ufix16
        txQ_data                          :   OUT   std_logic_vector(15 DOWNTO 0);  -- ufix16
        txI_valid                         :   OUT   std_logic;  -- ufix1
        txQ_valid                         :   OUT   std_logic;  -- ufix1
        rxI_ready                         :   OUT   std_logic;  -- ufix1
        rxQ_ready                         :   OUT   std_logic  -- ufix1
        );
END LTE_DOWNS_ip_dut;


ARCHITECTURE rtl OF LTE_DOWNS_ip_dut IS

  -- Component Declarations
  COMPONENT LTE_DOWNS_ip_src_LTE_DOWNSAMPLE_HDL
    PORT( clk                             :   IN    std_logic;
          clk_enable                      :   IN    std_logic;
          reset_x                         :   IN    std_logic;
          rxdatai_in                      :   IN    std_logic_vector(127 DOWNTO 0);  -- ufix128
          rxdataq_in                      :   IN    std_logic_vector(127 DOWNTO 0);  -- ufix128
          rxdatai_valid                   :   IN    std_logic;  -- ufix1
          rxdataq_valid                   :   IN    std_logic;  -- ufix1
          txdatai_ready                   :   IN    std_logic;  -- ufix1
          txdataq_ready                   :   IN    std_logic;  -- ufix1
          extdatasel_in                   :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32
          ce_out_0                        :   OUT   std_logic;  -- ufix1
          ce_out_1                        :   OUT   std_logic;  -- ufix1
          txI_data                        :   OUT   std_logic_vector(15 DOWNTO 0);  -- ufix16
          txQ_data                        :   OUT   std_logic_vector(15 DOWNTO 0);  -- ufix16
          txI_valid                       :   OUT   std_logic;  -- ufix1
          txQ_valid                       :   OUT   std_logic;  -- ufix1
          rxI_ready                       :   OUT   std_logic;  -- ufix1
          rxQ_ready                       :   OUT   std_logic  -- ufix1
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : LTE_DOWNS_ip_src_LTE_DOWNSAMPLE_HDL
    USE ENTITY work.LTE_DOWNS_ip_src_LTE_DOWNSAMPLE_HDL(rtl);

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL rxdatai_valid_sig                : std_logic;  -- ufix1
  SIGNAL rxdataq_valid_sig                : std_logic;  -- ufix1
  SIGNAL txdatai_ready_sig                : std_logic;  -- ufix1
  SIGNAL txdataq_ready_sig                : std_logic;  -- ufix1
  SIGNAL ce_out_0_sig                     : std_logic;  -- ufix1
  SIGNAL ce_out_1_sig                     : std_logic;  -- ufix1
  SIGNAL txI_data_sig                     : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL txQ_data_sig                     : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL txI_valid_sig                    : std_logic;  -- ufix1
  SIGNAL txQ_valid_sig                    : std_logic;  -- ufix1
  SIGNAL rxI_ready_sig                    : std_logic;  -- ufix1
  SIGNAL rxQ_ready_sig                    : std_logic;  -- ufix1

BEGIN
  u_LTE_DOWNS_ip_src_LTE_DOWNSAMPLE_HDL : LTE_DOWNS_ip_src_LTE_DOWNSAMPLE_HDL
    PORT MAP( clk => clk,
              clk_enable => enb,
              reset_x => reset_x,
              rxdatai_in => rxdatai_in,  -- ufix128
              rxdataq_in => rxdataq_in,  -- ufix128
              rxdatai_valid => rxdatai_valid_sig,  -- ufix1
              rxdataq_valid => rxdataq_valid_sig,  -- ufix1
              txdatai_ready => txdatai_ready_sig,  -- ufix1
              txdataq_ready => txdataq_ready_sig,  -- ufix1
              extdatasel_in => extdatasel_in,  -- sfix32
              ce_out_0 => ce_out_0_sig,  -- ufix1
              ce_out_1 => ce_out_1_sig,  -- ufix1
              txI_data => txI_data_sig,  -- ufix16
              txQ_data => txQ_data_sig,  -- ufix16
              txI_valid => txI_valid_sig,  -- ufix1
              txQ_valid => txQ_valid_sig,  -- ufix1
              rxI_ready => rxI_ready_sig,  -- ufix1
              rxQ_ready => rxQ_ready_sig  -- ufix1
              );

  rxdatai_valid_sig <= rxdatai_valid;

  rxdataq_valid_sig <= rxdataq_valid;

  txdatai_ready_sig <= txdatai_ready;

  txdataq_ready_sig <= txdataq_ready;

  enb <= dut_enable;

  ce_out_0 <= ce_out_0_sig;

  ce_out_1 <= ce_out_1_sig;

  txI_data <= txI_data_sig;

  txQ_data <= txQ_data_sig;

  txI_valid <= txI_valid_sig;

  txQ_valid <= txQ_valid_sig;

  rxI_ready <= rxI_ready_sig;

  rxQ_ready <= rxQ_ready_sig;

END rtl;

