-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\zynqRadioHWSWLTEMIBDetectorRFSoC2x2\ltehdlPBCHDecoder\LTE_MIB_H_ip_src_ltehdlPBCHDecoder_CRCGenCompute.vhd
-- Created: 2022-05-23 17:26:45
-- 
-- Generated by MATLAB 9.12 and HDL Coder 3.20
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: LTE_MIB_H_ip_src_ltehdlPBCHDecoder_CRCGenCompute
-- Source Path: ltehdlPBCHDecoder/BCH Decoder/CRC Decoder/CRCGenerator/CRCGenCompute
-- Hierarchy Level: 7
-- 
-- Compute the CRC CheckSum
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY LTE_MIB_H_ip_src_ltehdlPBCHDecoder_CRCGenCompute IS
  PORT( clk                               :   IN    std_logic;
        reset_x                           :   IN    std_logic;
        enb                               :   IN    std_logic;
        datainReg                         :   IN    std_logic;  -- ufix1
        validIn                           :   IN    std_logic;  -- ufix1
        processMsg                        :   IN    std_logic;  -- ufix1
        padZero                           :   IN    std_logic;  -- ufix1
        counter                           :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
        regClr                            :   IN    std_logic;  -- ufix1
        crcChecksum_0                     :   OUT   std_logic;  -- ufix1
        crcChecksum_1                     :   OUT   std_logic;  -- ufix1
        crcChecksum_2                     :   OUT   std_logic;  -- ufix1
        crcChecksum_3                     :   OUT   std_logic;  -- ufix1
        crcChecksum_4                     :   OUT   std_logic;  -- ufix1
        crcChecksum_5                     :   OUT   std_logic;  -- ufix1
        crcChecksum_6                     :   OUT   std_logic;  -- ufix1
        crcChecksum_7                     :   OUT   std_logic;  -- ufix1
        crcChecksum_8                     :   OUT   std_logic;  -- ufix1
        crcChecksum_9                     :   OUT   std_logic;  -- ufix1
        crcChecksum_10                    :   OUT   std_logic;  -- ufix1
        crcChecksum_11                    :   OUT   std_logic;  -- ufix1
        crcChecksum_12                    :   OUT   std_logic;  -- ufix1
        crcChecksum_13                    :   OUT   std_logic;  -- ufix1
        crcChecksum_14                    :   OUT   std_logic;  -- ufix1
        crcChecksum_15                    :   OUT   std_logic  -- ufix1
        );
END LTE_MIB_H_ip_src_ltehdlPBCHDecoder_CRCGenCompute;


ARCHITECTURE rtl OF LTE_MIB_H_ip_src_ltehdlPBCHDecoder_CRCGenCompute IS

  -- Signals
  SIGNAL counter_unsigned                 : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL xoredSel                         : std_logic;  -- ufix1
  SIGNAL dvalidin                         : std_logic;  -- ufix1
  SIGNAL tcsSel                           : std_logic;  -- ufix1
  SIGNAL csSel                            : std_logic;  -- ufix1
  SIGNAL checksumRst                      : std_logic;  -- ufix1
  SIGNAL rpadZero                         : std_logic;  -- ufix1
  SIGNAL dataSel                          : std_logic;  -- ufix1
  SIGNAL padingzeros                      : std_logic_vector(0 TO 15);  -- ufix1 [16]
  SIGNAL inputzeros                       : std_logic_vector(0 TO 14);  -- ufix1 [15]
  SIGNAL datamux                          : std_logic_vector(0 TO 15);  -- ufix1 [16]
  SIGNAL datacpt                          : std_logic_vector(0 TO 15);  -- ufix1 [16]
  SIGNAL datacpt_15                       : std_logic;  -- ufix1
  SIGNAL datacpt_14                       : std_logic;  -- ufix1
  SIGNAL datacpt_13                       : std_logic;  -- ufix1
  SIGNAL datacpt_12                       : std_logic;  -- ufix1
  SIGNAL datacpt_11                       : std_logic;  -- ufix1
  SIGNAL datacpt_10                       : std_logic;  -- ufix1
  SIGNAL datacpt_9                        : std_logic;  -- ufix1
  SIGNAL datacpt_8                        : std_logic;  -- ufix1
  SIGNAL datacpt_7                        : std_logic;  -- ufix1
  SIGNAL datacpt_6                        : std_logic;  -- ufix1
  SIGNAL datacpt_5                        : std_logic;  -- ufix1
  SIGNAL datacpt_4                        : std_logic;  -- ufix1
  SIGNAL datacpt_3                        : std_logic;  -- ufix1
  SIGNAL datacpt_2                        : std_logic;  -- ufix1
  SIGNAL datacpt_1                        : std_logic;  -- ufix1
  SIGNAL datacpt_0                        : std_logic;  -- ufix1
  SIGNAL finalXorValue                    : std_logic_vector(0 TO 15);  -- ufix1 [16]
  SIGNAL finalXorValue_0                  : std_logic;  -- ufix1
  SIGNAL finalXorValue_1                  : std_logic;  -- ufix1
  SIGNAL finalXorValue_2                  : std_logic;  -- ufix1
  SIGNAL finalXorValue_3                  : std_logic;  -- ufix1
  SIGNAL finalXorValue_4                  : std_logic;  -- ufix1
  SIGNAL finalXorValue_5                  : std_logic;  -- ufix1
  SIGNAL finalXorValue_6                  : std_logic;  -- ufix1
  SIGNAL finalXorValue_7                  : std_logic;  -- ufix1
  SIGNAL finalXorValue_8                  : std_logic;  -- ufix1
  SIGNAL finalXorValue_9                  : std_logic;  -- ufix1
  SIGNAL finalXorValue_10                 : std_logic;  -- ufix1
  SIGNAL finalXorValue_11                 : std_logic;  -- ufix1
  SIGNAL finalXorValue_12                 : std_logic;  -- ufix1
  SIGNAL finalXorValue_13                 : std_logic;  -- ufix1
  SIGNAL finalXorValue_14                 : std_logic;  -- ufix1
  SIGNAL finalXorValue_15                 : std_logic;  -- ufix1
  SIGNAL newChecksum                      : std_logic_vector(0 TO 15);  -- ufix1 [16]
  SIGNAL newChecksum_0                    : std_logic;  -- ufix1
  SIGNAL refelctCheckSum_15               : std_logic;  -- ufix1
  SIGNAL newChecksum_1                    : std_logic;  -- ufix1
  SIGNAL refelctCheckSum_14               : std_logic;  -- ufix1
  SIGNAL newChecksum_2                    : std_logic;  -- ufix1
  SIGNAL refelctCheckSum_13               : std_logic;  -- ufix1
  SIGNAL newChecksum_3                    : std_logic;  -- ufix1
  SIGNAL refelctCheckSum_12               : std_logic;  -- ufix1
  SIGNAL newChecksum_4                    : std_logic;  -- ufix1
  SIGNAL refelctCheckSum_11               : std_logic;  -- ufix1
  SIGNAL newChecksum_5                    : std_logic;  -- ufix1
  SIGNAL refelctCheckSum_10               : std_logic;  -- ufix1
  SIGNAL newChecksum_6                    : std_logic;  -- ufix1
  SIGNAL refelctCheckSum_9                : std_logic;  -- ufix1
  SIGNAL newChecksum_7                    : std_logic;  -- ufix1
  SIGNAL refelctCheckSum_8                : std_logic;  -- ufix1
  SIGNAL newChecksum_8                    : std_logic;  -- ufix1
  SIGNAL refelctCheckSum_7                : std_logic;  -- ufix1
  SIGNAL newChecksum_9                    : std_logic;  -- ufix1
  SIGNAL refelctCheckSum_6                : std_logic;  -- ufix1
  SIGNAL newChecksum_10                   : std_logic;  -- ufix1
  SIGNAL refelctCheckSum_5                : std_logic;  -- ufix1
  SIGNAL newChecksum_11                   : std_logic;  -- ufix1
  SIGNAL refelctCheckSum_4                : std_logic;  -- ufix1
  SIGNAL newChecksum_12                   : std_logic;  -- ufix1
  SIGNAL refelctCheckSum_3                : std_logic;  -- ufix1
  SIGNAL newChecksum_13                   : std_logic;  -- ufix1
  SIGNAL refelctCheckSum_2                : std_logic;  -- ufix1
  SIGNAL newChecksum_14                   : std_logic;  -- ufix1
  SIGNAL refelctCheckSum_1                : std_logic;  -- ufix1
  SIGNAL newChecksum_15                   : std_logic;  -- ufix1
  SIGNAL refelctCheckSum_0                : std_logic;  -- ufix1
  SIGNAL xoredChecksum                    : std_logic_vector(0 TO 15);  -- ufix1 [16]
  SIGNAL checksumReg                      : std_logic_vector(0 TO 15);  -- ufix1 [16]
  SIGNAL checksumReg_14                   : std_logic;  -- ufix1
  SIGNAL tcs_entry15                      : std_logic;  -- ufix1
  SIGNAL checksumReg_13                   : std_logic;  -- ufix1
  SIGNAL tcs_entry14                      : std_logic;  -- ufix1
  SIGNAL checksumReg_12                   : std_logic;  -- ufix1
  SIGNAL tcs_entry13                      : std_logic;  -- ufix1
  SIGNAL checksumReg_11                   : std_logic;  -- ufix1
  SIGNAL checksumReg_15                   : std_logic;  -- ufix1
  SIGNAL tcs_entry12                      : std_logic;  -- ufix1
  SIGNAL checksumReg_10                   : std_logic;  -- ufix1
  SIGNAL tcs_entry11                      : std_logic;  -- ufix1
  SIGNAL checksumReg_9                    : std_logic;  -- ufix1
  SIGNAL tcs_entry10                      : std_logic;  -- ufix1
  SIGNAL checksumReg_8                    : std_logic;  -- ufix1
  SIGNAL tcs_entry9                       : std_logic;  -- ufix1
  SIGNAL checksumReg_7                    : std_logic;  -- ufix1
  SIGNAL tcs_entry8                       : std_logic;  -- ufix1
  SIGNAL checksumReg_6                    : std_logic;  -- ufix1
  SIGNAL tcs_entry7                       : std_logic;  -- ufix1
  SIGNAL checksumReg_5                    : std_logic;  -- ufix1
  SIGNAL tcs_entry6                       : std_logic;  -- ufix1
  SIGNAL checksumReg_4                    : std_logic;  -- ufix1
  SIGNAL tcs_entry5                       : std_logic;  -- ufix1
  SIGNAL checksumReg_3                    : std_logic;  -- ufix1
  SIGNAL tcs_entry4                       : std_logic;  -- ufix1
  SIGNAL checksumReg_2                    : std_logic;  -- ufix1
  SIGNAL tcs_entry3                       : std_logic;  -- ufix1
  SIGNAL checksumReg_1                    : std_logic;  -- ufix1
  SIGNAL tcs_entry2                       : std_logic;  -- ufix1
  SIGNAL checksumReg_0                    : std_logic;  -- ufix1
  SIGNAL tcs_entry1                       : std_logic;  -- ufix1
  SIGNAL tcs_entry0                       : std_logic;  -- ufix1
  SIGNAL tchecksum                        : std_logic_vector(0 TO 15);  -- ufix1 [16]
  SIGNAL finalChecksum                    : std_logic_vector(0 TO 15);  -- ufix1 [16]
  SIGNAL crcChecksum                      : std_logic_vector(0 TO 15);  -- ufix1 [16]

BEGIN
  counter_unsigned <= unsigned(counter);

  
  xoredSel <= '1' WHEN counter_unsigned = to_unsigned(16#F#, 4) ELSE
      '0';

  validin_register_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        dvalidin <= '0';
      ELSIF enb = '1' THEN
        dvalidin <= validIn;
      END IF;
    END IF;
  END PROCESS validin_register_process;


  tcsSel <= processMsg AND dvalidin;

  csSel <= tcsSel OR padZero;

  checksumRst <= xoredSel OR regClr;

  rpadZero <=  NOT padZero;

  -- Selection signal: Select input data or pad zeros
  dataSel <= rpadZero AND dvalidin;

  -- Padding zeros
  padingzeros(0) <= '0';
  padingzeros(1) <= '0';
  padingzeros(2) <= '0';
  padingzeros(3) <= '0';
  padingzeros(4) <= '0';
  padingzeros(5) <= '0';
  padingzeros(6) <= '0';
  padingzeros(7) <= '0';
  padingzeros(8) <= '0';
  padingzeros(9) <= '0';
  padingzeros(10) <= '0';
  padingzeros(11) <= '0';
  padingzeros(12) <= '0';
  padingzeros(13) <= '0';
  padingzeros(14) <= '0';
  padingzeros(15) <= '0';

  inputzeros(0) <= '0';
  inputzeros(1) <= '0';
  inputzeros(2) <= '0';
  inputzeros(3) <= '0';
  inputzeros(4) <= '0';
  inputzeros(5) <= '0';
  inputzeros(6) <= '0';
  inputzeros(7) <= '0';
  inputzeros(8) <= '0';
  inputzeros(9) <= '0';
  inputzeros(10) <= '0';
  inputzeros(11) <= '0';
  inputzeros(12) <= '0';
  inputzeros(13) <= '0';
  inputzeros(14) <= '0';

  -- Prepare inputs for parallel CRC computation
  datamux(0) <= inputzeros(0);
  datamux(1) <= inputzeros(1);
  datamux(2) <= inputzeros(2);
  datamux(3) <= inputzeros(3);
  datamux(4) <= inputzeros(4);
  datamux(5) <= inputzeros(5);
  datamux(6) <= inputzeros(6);
  datamux(7) <= inputzeros(7);
  datamux(8) <= inputzeros(8);
  datamux(9) <= inputzeros(9);
  datamux(10) <= inputzeros(10);
  datamux(11) <= inputzeros(11);
  datamux(12) <= inputzeros(12);
  datamux(13) <= inputzeros(13);
  datamux(14) <= inputzeros(14);
  datamux(15) <= datainReg;

  -- Switch between input data and padded zeros
  
  datacpt <= padingzeros WHEN dataSel = '0' ELSE
      datamux;

  datacpt_15 <= datacpt(15);

  datacpt_14 <= datacpt(14);

  datacpt_13 <= datacpt(13);

  datacpt_12 <= datacpt(12);

  datacpt_11 <= datacpt(11);

  datacpt_10 <= datacpt(10);

  datacpt_9 <= datacpt(9);

  datacpt_8 <= datacpt(8);

  datacpt_7 <= datacpt(7);

  datacpt_6 <= datacpt(6);

  datacpt_5 <= datacpt(5);

  datacpt_4 <= datacpt(4);

  datacpt_3 <= datacpt(3);

  datacpt_2 <= datacpt(2);

  datacpt_1 <= datacpt(1);

  datacpt_0 <= datacpt(0);

  -- Compute finalXor
  finalXorValue(0) <= '0';
  finalXorValue(1) <= '0';
  finalXorValue(2) <= '0';
  finalXorValue(3) <= '0';
  finalXorValue(4) <= '0';
  finalXorValue(5) <= '0';
  finalXorValue(6) <= '0';
  finalXorValue(7) <= '0';
  finalXorValue(8) <= '0';
  finalXorValue(9) <= '0';
  finalXorValue(10) <= '0';
  finalXorValue(11) <= '0';
  finalXorValue(12) <= '0';
  finalXorValue(13) <= '0';
  finalXorValue(14) <= '0';
  finalXorValue(15) <= '0';

  finalXorValue_0 <= finalXorValue(0);

  finalXorValue_1 <= finalXorValue(1);

  finalXorValue_2 <= finalXorValue(2);

  finalXorValue_3 <= finalXorValue(3);

  finalXorValue_4 <= finalXorValue(4);

  finalXorValue_5 <= finalXorValue(5);

  finalXorValue_6 <= finalXorValue(6);

  finalXorValue_7 <= finalXorValue(7);

  finalXorValue_8 <= finalXorValue(8);

  finalXorValue_9 <= finalXorValue(9);

  finalXorValue_10 <= finalXorValue(10);

  finalXorValue_11 <= finalXorValue(11);

  finalXorValue_12 <= finalXorValue(12);

  finalXorValue_13 <= finalXorValue(13);

  finalXorValue_14 <= finalXorValue(14);

  finalXorValue_15 <= finalXorValue(15);

  newChecksum_0 <= newChecksum(0);

  refelctCheckSum_15 <= newChecksum_0 XOR finalXorValue_15;

  newChecksum_1 <= newChecksum(1);

  refelctCheckSum_14 <= newChecksum_1 XOR finalXorValue_14;

  newChecksum_2 <= newChecksum(2);

  refelctCheckSum_13 <= newChecksum_2 XOR finalXorValue_13;

  newChecksum_3 <= newChecksum(3);

  refelctCheckSum_12 <= newChecksum_3 XOR finalXorValue_12;

  newChecksum_4 <= newChecksum(4);

  refelctCheckSum_11 <= newChecksum_4 XOR finalXorValue_11;

  newChecksum_5 <= newChecksum(5);

  refelctCheckSum_10 <= newChecksum_5 XOR finalXorValue_10;

  newChecksum_6 <= newChecksum(6);

  refelctCheckSum_9 <= newChecksum_6 XOR finalXorValue_9;

  newChecksum_7 <= newChecksum(7);

  refelctCheckSum_8 <= newChecksum_7 XOR finalXorValue_8;

  newChecksum_8 <= newChecksum(8);

  refelctCheckSum_7 <= newChecksum_8 XOR finalXorValue_7;

  newChecksum_9 <= newChecksum(9);

  refelctCheckSum_6 <= newChecksum_9 XOR finalXorValue_6;

  newChecksum_10 <= newChecksum(10);

  refelctCheckSum_5 <= newChecksum_10 XOR finalXorValue_5;

  newChecksum_11 <= newChecksum(11);

  refelctCheckSum_4 <= newChecksum_11 XOR finalXorValue_4;

  newChecksum_12 <= newChecksum(12);

  refelctCheckSum_3 <= newChecksum_12 XOR finalXorValue_3;

  newChecksum_13 <= newChecksum(13);

  refelctCheckSum_2 <= newChecksum_13 XOR finalXorValue_2;

  newChecksum_14 <= newChecksum(14);

  refelctCheckSum_1 <= newChecksum_14 XOR finalXorValue_1;

  -- Reflect Checksum and make checksum LSB first
  newChecksum_15 <= newChecksum(15);

  refelctCheckSum_0 <= newChecksum_15 XOR finalXorValue_0;

  xoredChecksum(0) <= refelctCheckSum_0;
  xoredChecksum(1) <= refelctCheckSum_1;
  xoredChecksum(2) <= refelctCheckSum_2;
  xoredChecksum(3) <= refelctCheckSum_3;
  xoredChecksum(4) <= refelctCheckSum_4;
  xoredChecksum(5) <= refelctCheckSum_5;
  xoredChecksum(6) <= refelctCheckSum_6;
  xoredChecksum(7) <= refelctCheckSum_7;
  xoredChecksum(8) <= refelctCheckSum_8;
  xoredChecksum(9) <= refelctCheckSum_9;
  xoredChecksum(10) <= refelctCheckSum_10;
  xoredChecksum(11) <= refelctCheckSum_11;
  xoredChecksum(12) <= refelctCheckSum_12;
  xoredChecksum(13) <= refelctCheckSum_13;
  xoredChecksum(14) <= refelctCheckSum_14;
  xoredChecksum(15) <= refelctCheckSum_15;

  checksumReg_14 <= checksumReg(14);

  -- Compute checksum element16
  tcs_entry15 <= checksumReg_14 XOR datacpt_0;

  checksumReg_13 <= checksumReg(13);

  -- Compute checksum element15
  tcs_entry14 <= checksumReg_13 XOR datacpt_1;

  checksumReg_12 <= checksumReg(12);

  -- Compute checksum element14
  tcs_entry13 <= checksumReg_12 XOR datacpt_2;

  checksumReg_11 <= checksumReg(11);

  -- Compute checksum element13
  tcs_entry12 <= datacpt_3 XOR (checksumReg_15 XOR checksumReg_11);

  checksumReg_10 <= checksumReg(10);

  -- Compute checksum element12
  tcs_entry11 <= checksumReg_10 XOR datacpt_4;

  checksumReg_9 <= checksumReg(9);

  -- Compute checksum element11
  tcs_entry10 <= checksumReg_9 XOR datacpt_5;

  checksumReg_8 <= checksumReg(8);

  -- Compute checksum element10
  tcs_entry9 <= checksumReg_8 XOR datacpt_6;

  checksumReg_7 <= checksumReg(7);

  -- Compute checksum element9
  tcs_entry8 <= checksumReg_7 XOR datacpt_7;

  checksumReg_6 <= checksumReg(6);

  -- Compute checksum element8
  tcs_entry7 <= checksumReg_6 XOR datacpt_8;

  checksumReg_5 <= checksumReg(5);

  -- Compute checksum element7
  tcs_entry6 <= checksumReg_5 XOR datacpt_9;

  checksumReg_4 <= checksumReg(4);

  -- Compute checksum element6
  tcs_entry5 <= datacpt_10 XOR (checksumReg_15 XOR checksumReg_4);

  checksumReg_3 <= checksumReg(3);

  -- Compute checksum element5
  tcs_entry4 <= checksumReg_3 XOR datacpt_11;

  checksumReg_2 <= checksumReg(2);

  -- Compute checksum element4
  tcs_entry3 <= checksumReg_2 XOR datacpt_12;

  checksumReg_1 <= checksumReg(1);

  -- Compute checksum element3
  tcs_entry2 <= checksumReg_1 XOR datacpt_13;

  checksumReg_0 <= checksumReg(0);

  -- Compute checksum element2
  tcs_entry1 <= checksumReg_0 XOR datacpt_14;

  checksumReg_15 <= checksumReg(15);

  -- Compute checksum element1
  -- 
  -- Checksum selection signal
  tcs_entry0 <= checksumReg_15 XOR datacpt_15;

  tchecksum(0) <= tcs_entry0;
  tchecksum(1) <= tcs_entry1;
  tchecksum(2) <= tcs_entry2;
  tchecksum(3) <= tcs_entry3;
  tchecksum(4) <= tcs_entry4;
  tchecksum(5) <= tcs_entry5;
  tchecksum(6) <= tcs_entry6;
  tchecksum(7) <= tcs_entry7;
  tchecksum(8) <= tcs_entry8;
  tchecksum(9) <= tcs_entry9;
  tchecksum(10) <= tcs_entry10;
  tchecksum(11) <= tcs_entry11;
  tchecksum(12) <= tcs_entry12;
  tchecksum(13) <= tcs_entry13;
  tchecksum(14) <= tcs_entry14;
  tchecksum(15) <= tcs_entry15;

  checksum_register_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        checksumReg <= (OTHERS => '0');
      ELSIF enb = '1' THEN
        IF checksumRst = '1' THEN
          checksumReg <= (OTHERS => '0');
        ELSE 
          checksumReg <= finalChecksum;
        END IF;
      END IF;
    END IF;
  END PROCESS checksum_register_process;


  -- Update checksum register for valid inputs
  
  newChecksum <= checksumReg WHEN csSel = '0' ELSE
      tchecksum;

  -- Xor after computing the checksum
  
  finalChecksum <= newChecksum WHEN xoredSel = '0' ELSE
      xoredChecksum;

  -- 1
  outputchecksum_register_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        crcChecksum <= (OTHERS => '0');
      ELSIF enb = '1' AND xoredSel = '1' THEN
        crcChecksum <= finalChecksum;
      END IF;
    END IF;
  END PROCESS outputchecksum_register_process;


  crcChecksum_0 <= crcChecksum(0);

  crcChecksum_1 <= crcChecksum(1);

  crcChecksum_2 <= crcChecksum(2);

  crcChecksum_3 <= crcChecksum(3);

  crcChecksum_4 <= crcChecksum(4);

  crcChecksum_5 <= crcChecksum(5);

  crcChecksum_6 <= crcChecksum(6);

  crcChecksum_7 <= crcChecksum(7);

  crcChecksum_8 <= crcChecksum(8);

  crcChecksum_9 <= crcChecksum(9);

  crcChecksum_10 <= crcChecksum(10);

  crcChecksum_11 <= crcChecksum(11);

  crcChecksum_12 <= crcChecksum(12);

  crcChecksum_13 <= crcChecksum(13);

  crcChecksum_14 <= crcChecksum(14);

  crcChecksum_15 <= crcChecksum(15);

END rtl;

