-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\zynqRadioHWSWLTEMIBDetectorRFSoC2x2\ltehdlPBCHDecoder\LTE_MIB_H_ip_src_ltehdlPBCHDecoder_MATLAB_Function.vhd
-- Created: 2022-05-23 17:26:45
-- 
-- Generated by MATLAB 9.12 and HDL Coder 3.20
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: LTE_MIB_H_ip_src_ltehdlPBCHDecoder_MATLAB_Function
-- Source Path: ltehdlPBCHDecoder/Gold Sequence Generator/LFSR1/MATLAB Function
-- Hierarchy Level: 6
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY LTE_MIB_H_ip_src_ltehdlPBCHDecoder_MATLAB_Function IS
  PORT( u                                 :   IN    std_logic_vector(30 DOWNTO 0);  -- ufix31
        y                                 :   OUT   std_logic_vector(30 DOWNTO 0)  -- ufix31
        );
END LTE_MIB_H_ip_src_ltehdlPBCHDecoder_MATLAB_Function;


ARCHITECTURE rtl OF LTE_MIB_H_ip_src_ltehdlPBCHDecoder_MATLAB_Function IS

  -- Signals
  SIGNAL u_unsigned                       : unsigned(30 DOWNTO 0);  -- ufix31
  SIGNAL y_tmp                            : unsigned(30 DOWNTO 0);  -- ufix31

BEGIN
  u_unsigned <= unsigned(u);

  y_tmp <= to_unsigned(16#00000001#, 31);

  y <= std_logic_vector(y_tmp);

END rtl;

