-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\zynqRadioHWSWLTEMIBDetectorRFSoC2x2\LTE_MIB_H_ip_src_FilterTapSystolicWvldin_block6.vhd
-- Created: 2022-05-23 17:26:55
-- 
-- Generated by MATLAB 9.12 and HDL Coder 3.20
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: LTE_MIB_H_ip_src_FilterTapSystolicWvldin_block6
-- Source Path: zynqRadioHWSWLTEMIBDetectorRFSoC2x2/LTE_MIB_HDL/Preprocessor/Vector Decimator/Decimation/FIR Decimation 
-- HDL Optimized1/FilterBank/subFilter/FilterTapSystolicWvldi
-- Hierarchy Level: 7
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY LTE_MIB_H_ip_src_FilterTapSystolicWvldin_block6 IS
  PORT( clk                               :   IN    std_logic;
        enb                               :   IN    std_logic;
        dinReg2_7_re                      :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
        coefIn_0                          :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En16
        addin                             :   IN    std_logic_vector(47 DOWNTO 0);  -- sfix48_En31
        dinRegVld                         :   IN    std_logic;
        dinDly2                           :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
        tapout                            :   OUT   std_logic_vector(47 DOWNTO 0)  -- sfix48_En31
        );
END LTE_MIB_H_ip_src_FilterTapSystolicWvldin_block6;


ARCHITECTURE rtl OF LTE_MIB_H_ip_src_FilterTapSystolicWvldin_block6 IS

  -- Signals
  SIGNAL dinReg2_7_re_signed              : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL coefIn_0_signed                  : signed(15 DOWNTO 0);  -- sfix16_En16
  SIGNAL addin_signed                     : signed(47 DOWNTO 0);  -- sfix48_En31
  SIGNAL fTap_din_reg1                    : signed(15 DOWNTO 0) := to_signed(16#0000#, 16);  -- sfix16
  SIGNAL fTap_coef_reg1                   : signed(15 DOWNTO 0) := to_signed(16#0000#, 16);  -- sfix16
  SIGNAL fTap_din_reg2                    : signed(15 DOWNTO 0) := to_signed(16#0000#, 16);  -- sfix16
  SIGNAL fTap_coef_reg2                   : signed(15 DOWNTO 0) := to_signed(16#0000#, 16);  -- sfix16
  SIGNAL fTap_mult_reg                    : signed(31 DOWNTO 0) := to_signed(0, 32);  -- sfix32
  SIGNAL fTap_addout_reg                  : signed(47 DOWNTO 0) := to_signed(0, 48);  -- sfix48
  SIGNAL fTap_din_reg1_next               : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL fTap_coef_reg1_next              : signed(15 DOWNTO 0);  -- sfix16_En16
  SIGNAL fTap_din_reg2_next               : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL fTap_coef_reg2_next              : signed(15 DOWNTO 0);  -- sfix16_En16
  SIGNAL fTap_mult_reg_next               : signed(31 DOWNTO 0);  -- sfix32_En31
  SIGNAL fTap_addout_reg_next             : signed(47 DOWNTO 0);  -- sfix48_En31
  SIGNAL dinDly2_tmp                      : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL tapout_tmp                       : signed(47 DOWNTO 0);  -- sfix48_En31

BEGIN
  dinReg2_7_re_signed <= signed(dinReg2_7_re);

  coefIn_0_signed <= signed(coefIn_0);

  addin_signed <= signed(addin);

  -- FilterTapSystlicWvldIn
  fTap_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        fTap_din_reg1 <= fTap_din_reg1_next;
        fTap_coef_reg1 <= fTap_coef_reg1_next;
        fTap_din_reg2 <= fTap_din_reg2_next;
        fTap_coef_reg2 <= fTap_coef_reg2_next;
        fTap_mult_reg <= fTap_mult_reg_next;
        fTap_addout_reg <= fTap_addout_reg_next;
      END IF;
    END IF;
  END PROCESS fTap_process;

  fTap_output : PROCESS (addin_signed, coefIn_0_signed, dinReg2_7_re_signed, dinRegVld, fTap_addout_reg,
       fTap_coef_reg1, fTap_coef_reg2, fTap_din_reg1, fTap_din_reg2,
       fTap_mult_reg)
    VARIABLE add_cast : signed(47 DOWNTO 0);
  BEGIN
    add_cast := to_signed(0, 48);
    fTap_din_reg1_next <= fTap_din_reg1;
    fTap_coef_reg1_next <= fTap_coef_reg1;
    fTap_din_reg2_next <= fTap_din_reg2;
    fTap_coef_reg2_next <= fTap_coef_reg2;
    fTap_mult_reg_next <= fTap_mult_reg;
    fTap_addout_reg_next <= fTap_addout_reg;
    IF dinRegVld = '1' THEN 
      add_cast := resize(fTap_mult_reg, 48);
      fTap_addout_reg_next <= add_cast + addin_signed;
      fTap_mult_reg_next <= fTap_din_reg2 * fTap_coef_reg2;
      fTap_din_reg2_next <= fTap_din_reg1;
      fTap_coef_reg2_next <= fTap_coef_reg1;
      fTap_din_reg1_next <= dinReg2_7_re_signed;
      fTap_coef_reg1_next <= coefIn_0_signed;
    END IF;
    dinDly2_tmp <= fTap_din_reg2;
    tapout_tmp <= fTap_addout_reg;
  END PROCESS fTap_output;


  dinDly2 <= std_logic_vector(dinDly2_tmp);

  tapout <= std_logic_vector(tapout_tmp);

END rtl;

