-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\zynqRadioHWSWLTEMIBDetectorRFSoC2x2\ltehdlDownlinkSyncDemod\LTE_MIB_H_ip_src_ltehdlDownlinkSyncDemod_ThresholdLimiter_block.vhd
-- Created: 2022-05-23 17:26:44
-- 
-- Generated by MATLAB 9.12 and HDL Coder 3.20
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: LTE_MIB_H_ip_src_ltehdlDownlinkSyncDemod_ThresholdLimiter_block
-- Source Path: ltehdlDownlinkSyncDemod/Sync Signal Search/SSS Searcher/Max Likelihood SSS/SSS_Dot_Product/ThresholdLimiter
-- Hierarchy Level: 7
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY LTE_MIB_H_ip_src_ltehdlDownlinkSyncDemod_ThresholdLimiter_block IS
  PORT( x                                 :   IN    std_logic_vector(35 DOWNTO 0);  -- ufix36
        y                                 :   OUT   std_logic_vector(35 DOWNTO 0)  -- sfix36_En26
        );
END LTE_MIB_H_ip_src_ltehdlDownlinkSyncDemod_ThresholdLimiter_block;


ARCHITECTURE rtl OF LTE_MIB_H_ip_src_ltehdlDownlinkSyncDemod_ThresholdLimiter_block IS

  -- Signals
  SIGNAL x_signed                         : signed(35 DOWNTO 0);  -- sfix36_En26
  SIGNAL y_tmp                            : signed(35 DOWNTO 0);  -- sfix36_En26

BEGIN
  x_signed <= signed(x);

  -- Apply a lower limit to the threshold.
  -- Threshold is computed by summing across 62 samples.
  -- Set lower limit to be equivalent of all 62 samples
  -- having their LSB set to 1 and all others set to 0. 
  
  y_tmp <= to_signed(62, 36) WHEN x_signed < to_signed(62, 36) ELSE
      x_signed;

  y <= std_logic_vector(y_tmp);

END rtl;

